"""empty message

Revision ID: 2fca16c197c6
Revises: 5316ddf879cb
Create Date: 2014-02-24 13:11:28.011991

"""

# revision identifiers, used by Alembic.
revision = '2fca16c197c6'
down_revision = '5316ddf879cb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    ### end Alembic commands ###
