"""empty message

Revision ID: 474294665d6a
Revises: 23885149f982
Create Date: 2014-02-24 14:59:43.239580

"""

# revision identifiers, used by Alembic.
revision = '474294665d6a'
down_revision = '23885149f982'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    ### end Alembic commands ###
