"""empty message

Revision ID: 54fe000df0d8
Revises: 5a3ef7b3b82c
Create Date: 2014-02-22 23:50:15.159431

"""

# revision identifiers, used by Alembic.
revision = '54fe000df0d8'
down_revision = '5a3ef7b3b82c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
