"""empty message

Revision ID: b429e0caa1
Revises: 54fe000df0d8
Create Date: 2014-02-23 00:27:49.518484

"""

# revision identifiers, used by Alembic.
revision = 'b429e0caa1'
down_revision = '54fe000df0d8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=64), nullable=True))
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_email', 'users')
    op.drop_column('users', 'email')
    ### end Alembic commands ###
